apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-starter
  namespace: learn
  labels:
    app: docker-starter
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: docker-starter
  template:
    metadata:
      labels:
        app: docker-starter
    spec:
      containers:
      - name: docker-starter
        image: aa
        ports:
        - containerPort: 9003
        readinessProbe:
          tcpSocket:
            port: 9003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9003
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: docker-starter-svc
  namespace: learn
spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: docker-starter

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: docker-starter-hpa-c
  namespace: learn
  labels:
    app: docker-starter-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker-starter
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: docker-starter-hpa-m
  namespace: learn
  labels:
    app: docker-starter-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker-starter
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
